### PR TITLE
use latest Ruby2.4 version

### PR DESCRIPTION
**Pull request by takkanm**

### CODE REVIEW

**Comment by koic** [comment]
Ruby 2.4.1 isn't available on Travis CI. We will wait and see for a little more.

http://rubies.travis-ci.org

**Comment by takkanm** [comment]
> Ruby 2.4.1 isn't available on Travis CI. We will wait and see for a little more.

nrhd. Thanks for your infomation.

**Comment by koic** [comment]
Ruby 2.4.1 is now available on Travis CI. I will try this build again.

http://rubies.travis-ci.org

**Comment by koic** [comment]
This build was successful. I was merged this PR. Thanks.

**Pull request merged**
