### PR TITLE
Highlighten SQL by highlight.js

### PR DESCRIPTION
**Pull request by joker1007**
added [highlight.js](https://highlightjs.org/ "highlight.js") in order to highlight SQL preview.

### CODE REVIEW

**Comment by moro** [comment]
Oh, so huge CSS/JS !!

I'm better at Ruby than JS, so I try to [rouge](https://github.com/jneen/rouge) instead to maintain long time. How do you think about this?

**Comment by joker1007** [comment]
I think that Ruby way is more gem friendly than JS way, but JS way is easier than Ruby way for me.
I only want to highlight SQL syntax, and so the method does not matter.

You may close this PR.

**Comment by joker1007** [comment]
If you are busy to do it, I will do `rouge` version.

**Comment by moro** [comment]
Pure ruby rouge version was merged by @joker1007 himself at #65.
Thanks !!

**Pull request closed without merging**
